---
- name: Install necessary apps to amazon web server
  hosts: web
  sudo: True
  remote_user: ubuntu
  vars_files:
    - ursa_blogger_prod_vars.vars
  environment: env
  tasks:
    - name: install apps
      apt: name={{ item }} state=present update_cache=yes
      with_items:
        - libapache2-mod-wsgi
        - apache2
        - python-dev
        - python-setuptools
        - libpq-dev
        - python-pip
        - git

    - name: write apache virtual host config
      copy: src=files/000-default.conf dest=/etc/apache2/sites-available/000-default.conf

    - name: install virtualenv
      pip: name=virtualenv

    - name: copy private key
      copy: src=~/.keys/amazonPrivateKey.pem dest=/root/.ssh/amazonPrivateKey.pem mode=0600 owner=ubuntu group=ubuntu

    - name: copy github private key
      copy: src=~/.ssh/id_rsa dest=/root/.ssh/id_rsa mode=0600 owner=ubuntu group=ubuntu

    - name: create app directory
      file: path=/var/www/bear_blog_env/bear_blog_project/ state=directory

    - name: clone bear_blog_project git repository
      git:
        repo=git@github.com:beartrickey/bear_blog_project.git
        dest=/var/www/bear_blog_env/bear_blog_project
        force=yes
        accept_hostkey=yes
        key_file=/root/.ssh/id_rsa
        version=master

    - name: pip install requirements
      pip: requirements=/var/www/bear_blog_env/bear_blog_project/requirements.txt virtualenv=/var/www/bear_blog_env/

    - name: stop apache
      shell: "/usr/sbin/apache2ctl stop"

    - name: start apache
      environment: env
      shell: "/usr/sbin/apache2ctl start"

